### ISSUE TITLE
Пустая адресная строка

### ISSUE THREAD

**Issue by victor-lu** [dchest/minimal-newtab#1]
В 10 версии Chrome адресная на странице открытой с новой вкладки пустая.
Поскольку на лицо злая бага гугла предлагаю злой костыль:
добавить атрибуты ссылке - onclick='window.close();' target='_blank'c

**Comment by dchest** [comment]
Хм, у меня 10.0.648.204 и в адресной строке — адрес, как положено. Может ссылка какая-то особенная, можно пример?

**Comment by dchest** [comment]
Ответ по почте с русским языком, видимо, не работает...

**Comment by victor-lu** [comment]
Да, и я ничего кроме вопроса в почте не увидел =)

Проблема проявлялась на всех ссылках, в том числе и на Gmail. Судя по последнему комментарию на странице расширения - не один я столкнулся с такой проблемой. Удаление всех "данных о просмотренных страницах" и удаление и добавление расширения - решили проблему.

Могу предположить только, что когда-то, с обновлением хрома, что-то сломалось. Повторить не могу =)

**Comment by dchest** [comment]
Отлично, спасибо за объяснение.
